import re
import openpyxl
import openai
import time
string = r"""make a 4 paragraph blog about flights from lax to zacatecas mexico --first h2:How much are flights from lax to zacatecas mexico --next h2: How long are flights from lax to zacatecas mexico ( Use (2h58min)) next h2: What’s the cheapest day for flights from lax to zacatecas mexico (use Tuseday) --next h2: How far are the flights from lax to zacatecas mexico ( Use 1,307.40) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from lax to zacatecas mexico
make a 4 paragraph blog about flights from dallas to zacatecas mexico --first h2:How much are flights from dallas to zacatecas mexico --next h2: How long are flights from dallas to zacatecas mexico ( Use (2h16min)) next h2: What’s the cheapest day for flights from dallas to zacatecas mexico (use Tuseday) --next h2: How far are the flights from dallas to zacatecas mexico ( Use 936.75) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from dallas to zacatecas mexico
make a 4 paragraph blog about flights from denver to zacatecas mexico --first h2:How much are flights from denver to zacatecas mexico --next h2: How long are flights from denver to zacatecas mexico ( Use (3h0min)) next h2: What’s the cheapest day for flights from denver to zacatecas mexico (use Tuseday) --next h2: How far are the flights from denver to zacatecas mexico ( Use 1,327.51) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from denver to zacatecas mexico
make a 4 paragraph blog about cheap flights from chicago to zacatecas mexico --first h2:How much are cheap flights from chicago to zacatecas mexico --next h2: How long are cheap flights from chicago to zacatecas mexico ( Use (3h46min)) next h2: What’s the cheapest day for cheap flights from chicago to zacatecas mexico (use Tuseday) --next h2: How far are the cheap flights from chicago to zacatecas mexico ( Use 1,731.24) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about cheap flights from chicago to zacatecas mexico
make a 4 paragraph blog about Flights from Los Angeles to Zacatecas, Mexico --first h2:How much are Flights from Los Angeles to Zacatecas, Mexico --next h2: How long are Flights from Los Angeles to Zacatecas, Mexico ( Use (2h58min)) next h2: What’s the cheapest day for Flights from Los Angeles to Zacatecas, Mexico (use Tuseday) --next h2: How far are the Flights from Los Angeles to Zacatecas, Mexico ( Use 1,305.26) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Los Angeles to Zacatecas, Mexico
make a 4 paragraph blog about Flights from Tijuana to Torreon Mexico --first h2:How much are Flights from Tijuana to Torreon Mexico --next h2: How long are Flights from Tijuana to Torreon Mexico ( Use (2h37min)) next h2: What’s the cheapest day for Flights from Tijuana to Torreon Mexico (use Tuseday) --next h2: How far are the Flights from Tijuana to Torreon Mexico ( Use 950.1) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Tijuana to Torreon Mexico
make a 4 paragraph blog about flights from san antonio to toluca mexico --first h2:How much are flights from san antonio to toluca mexico --next h2: How long are flights from san antonio to toluca mexico ( Use (1h48min)) next h2: What’s the cheapest day for flights from san antonio to toluca mexico (use Tuseday) --next h2: How far are the flights from san antonio to toluca mexico ( Use 688.39) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from san antonio to toluca mexico
make a 4 paragraph blog about cheap flights from houston to tampico mexico --first h2:How much are cheap flights from houston to tampico mexico --next h2: How long are cheap flights from houston to tampico mexico ( Use (1h54min)) next h2: What’s the cheapest day for cheap flights from houston to tampico mexico (use Tuseday) --next h2: How far are the cheap flights from houston to tampico mexico ( Use 747.97) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about cheap flights from houston to tampico mexico
make a 4 paragraph blog about Chicago to San Luis Potosi, Mexico flights --first h2:How much are Chicago to San Luis Potosi, Mexico flights --next h2: How long are Chicago to San Luis Potosi, Mexico flights ( Use (3h46min)) next h2: What’s the cheapest day for Chicago to San Luis Potosi, Mexico flights (use Tuseday) --next h2: How far are the Chicago to San Luis Potosi, Mexico flights ( Use 1733.44) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Chicago to San Luis Potosi, Mexico flights
make a 4 paragraph blog about flights from san antonio to san luis potosi mexico --first h2:How much are flights from san antonio to san luis potosi mexico --next h2: How long are flights from san antonio to san luis potosi mexico ( Use (1h47min)) next h2: What’s the cheapest day for flights from san antonio to san luis potosi mexico (use Tuseday) --next h2: How far are the flights from san antonio to san luis potosi mexico ( Use 683.02) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from san antonio to san luis potosi mexico
make a 4 paragraph blog about flights from dallas to queretaro mexico --first h2:How much are flights from dallas to queretaro mexico --next h2: How long are flights from dallas to queretaro mexico ( Use (2h15min)) next h2: What’s the cheapest day for flights from dallas to queretaro mexico (use Tuseday) --next h2: How far are the flights from dallas to queretaro mexico ( Use 931.18) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from dallas to queretaro mexico
make a 4 paragraph blog about Flights from Austin to Queretaro, Mexico --first h2:How much are Flights from Austin to Queretaro, Mexico --next h2: How long are Flights from Austin to Queretaro, Mexico ( Use (1h55min)) next h2: What’s the cheapest day for Flights from Austin to Queretaro, Mexico (use Tuseday) --next h2: How far are the Flights from Austin to Queretaro, Mexico ( Use 750.13) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Austin to Queretaro, Mexico
make a 4 paragraph blog about Flights from Dallas TX to Queretaro Mexico --first h2:How much are Flights from Dallas TX to Queretaro Mexico --next h2: How long are Flights from Dallas TX to Queretaro Mexico ( Use (2h15min)) next h2: What’s the cheapest day for Flights from Dallas TX to Queretaro Mexico (use Tuseday) --next h2: How far are the Flights from Dallas TX to Queretaro Mexico ( Use 931.18) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Dallas TX to Queretaro Mexico
make a 4 paragraph blog about Flights from San Antonio Texas to Queretaro Mexico --first h2:How much are Flights from San Antonio Texas to Queretaro Mexico --next h2: How long are Flights from San Antonio Texas to Queretaro Mexico ( Use (1h48min)) next h2: What’s the cheapest day for Flights from San Antonio Texas to Queretaro Mexico (use Tuseday) --next h2: How far are the Flights from San Antonio Texas to Queretaro Mexico ( Use 688.39) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from San Antonio Texas to Queretaro Mexico
make a 4 paragraph blog about Flights from Las Vegas to Puerto Vallarta Mexico --first h2:How much are Flights from Las Vegas to Puerto Vallarta Mexico --next h2: How long are Flights from Las Vegas to Puerto Vallarta Mexico ( Use (2h48min)) next h2: What’s the cheapest day for Flights from Las Vegas to Puerto Vallarta Mexico (use Tuseday) --next h2: How far are the Flights from Las Vegas to Puerto Vallarta Mexico ( Use 1,223.23) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Las Vegas to Puerto Vallarta Mexico
make a 4 paragraph blog about Flights from San Francisco to Puerto Vallarta Mexico --first h2:How much are Flights from San Francisco to Puerto Vallarta Mexico --next h2: How long are Flights from San Francisco to Puerto Vallarta Mexico ( Use (3h27min)) next h2: What’s the cheapest day for Flights from San Francisco to Puerto Vallarta Mexico (use Tuseday) --next h2: How far are the Flights from San Francisco to Puerto Vallarta Mexico ( Use 1,563.39) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from San Francisco to Puerto Vallarta Mexico
make a 4 paragraph blog about Flights from Atlanta to Puerto Vallarta Mexico --first h2:How much are Flights from Atlanta to Puerto Vallarta Mexico --next h2: How long are Flights from Atlanta to Puerto Vallarta Mexico ( Use (3h27min)) next h2: What’s the cheapest day for Flights from Atlanta to Puerto Vallarta Mexico (use Tuseday) --next h2: How far are the Flights from Atlanta to Puerto Vallarta Mexico ( Use 1,562.94) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Atlanta to Puerto Vallarta Mexico
make a 4 paragraph blog about Flights from Phoenix to Puerto Penasco Mexico --first h2:How much are Flights from Phoenix to Puerto Penasco Mexico --next h2: How long are Flights from Phoenix to Puerto Penasco Mexico ( Use (0h42min)) next h2: What’s the cheapest day for Flights from Phoenix to Puerto Penasco Mexico (use Tuseday) --next h2: How far are the Flights from Phoenix to Puerto Penasco Mexico ( Use 113.20) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Phoenix to Puerto Penasco Mexico
make a 4 paragraph blog about flights from chicago to morelia mexico --first h2:How much are flights from chicago to morelia mexico --next h2: How long are flights from chicago to morelia mexico ( Use (3h41min)) next h2: What’s the cheapest day for flights from chicago to morelia mexico (use Tuseday) --next h2: How far are the flights from chicago to morelia mexico ( Use 1,683.61) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from chicago to morelia mexico
make a 4 paragraph blog about flights from sacramento to morelia mexico --first h2:How much are flights from sacramento to morelia mexico --next h2: How long are flights from sacramento to morelia mexico ( Use (4h3min)) next h2: What’s the cheapest day for flights from sacramento to morelia mexico (use Tuseday) --next h2: How far are the flights from sacramento to morelia mexico ( Use 1,882.18) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from sacramento to morelia mexico
make a 4 paragraph blog about Flights from San Francisco to Morelia, Mexico --first h2:How much are Flights from San Francisco to Morelia, Mexico --next h2: How long are Flights from San Francisco to Morelia, Mexico ( Use (4h4min)) next h2: What’s the cheapest day for Flights from San Francisco to Morelia, Mexico (use Tuseday) --next h2: How far are the Flights from San Francisco to Morelia, Mexico ( Use 1,889.23) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from San Francisco to Morelia, Mexico
make a 4 paragraph blog about Cheap flights from LAX to Morelia, Mexico --first h2:How much are Cheap flights from LAX to Morelia, Mexico --next h2: How long are Cheap flights from LAX to Morelia, Mexico ( Use (3h26min)) next h2: What’s the cheapest day for Cheap flights from LAX to Morelia, Mexico (use Tuseday) --next h2: How far are the Cheap flights from LAX to Morelia, Mexico ( Use 1,552.85) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Cheap flights from LAX to Morelia, Mexico
make a 4 paragraph blog about cheap flights to monterrey mexico from dallas --first h2:How much are cheap flights to monterrey mexico from dallas --next h2: How long are cheap flights to monterrey mexico from dallas ( Use (1h29min)) next h2: What’s the cheapest day for cheap flights to monterrey mexico from dallas (use Tuseday) --next h2: How far are the cheap flights to monterrey mexico from dallas ( Use 523.98) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about cheap flights to monterrey mexico from dallas
make a 4 paragraph blog about flights from harlingen to monterrey mexico --first h2:How much are flights from harlingen to monterrey mexico --next h2: How long are flights from harlingen to monterrey mexico ( Use (0h47min)) next h2: What’s the cheapest day for flights from harlingen to monterrey mexico (use Tuseday) --next h2: How far are the flights from harlingen to monterrey mexico ( Use 152.66) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from harlingen to monterrey mexico
make a 4 paragraph blog about Flights to Monterrey Mexico from Houston --first h2:How much are Flights to Monterrey Mexico from Houston --next h2: How long are Flights to Monterrey Mexico from Houston ( Use (1h15min)) next h2: What’s the cheapest day for Flights to Monterrey Mexico from Houston (use Tuseday) --next h2: How far are the Flights to Monterrey Mexico from Houston ( Use 399.54) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights to Monterrey Mexico from Houston
make a 4 paragraph blog about cheap flights from chicago to monterrey mexico --first h2:How much are cheap flights from chicago to monterrey mexico --next h2: How long are cheap flights from chicago to monterrey mexico ( Use (2h59min)) next h2: What’s the cheapest day for cheap flights from chicago to monterrey mexico (use Tuseday) --next h2: How far are the cheap flights from chicago to monterrey mexico ( Use 1,316.07) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about cheap flights from chicago to monterrey mexico
make a 4 paragraph blog about Flights from Denver to Mazatlan, Mexico --first h2:How much are Flights from Denver to Mazatlan, Mexico --next h2: How long are Flights from Denver to Mazatlan, Mexico ( Use (2h59min)) next h2: What’s the cheapest day for Flights from Denver to Mazatlan, Mexico (use Tuseday) --next h2: How far are the Flights from Denver to Mazatlan, Mexico ( Use 1,313.00) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Denver to Mazatlan, Mexico
make a 4 paragraph blog about Flights from San Diego to Mazatlan Mexico --first h2:How much are Flights from San Diego to Mazatlan Mexico --next h2: How long are Flights from San Diego to Mazatlan Mexico ( Use (2h35min)) next h2: What’s the cheapest day for Flights from San Diego to Mazatlan Mexico (use Tuseday) --next h2: How far are the Flights from San Diego to Mazatlan Mexico ( Use 1,106.57) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from San Diego to Mazatlan Mexico
make a 4 paragraph blog about Flights from Seattle to Los Cabos, Mexico --first h2:How much are Flights from Seattle to Los Cabos, Mexico --next h2: How long are Flights from Seattle to Los Cabos, Mexico ( Use (3h57min)) next h2: What’s the cheapest day for Flights from Seattle to Los Cabos, Mexico (use Tuseday) --next h2: How far are the Flights from Seattle to Los Cabos, Mexico ( Use 1,824.61) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Seattle to Los Cabos, Mexico
make a 4 paragraph blog about flights from phoenix to loreto mexico --first h2:How much are flights from phoenix to loreto mexico --next h2: How long are flights from phoenix to loreto mexico ( Use (2h28min)) next h2: What’s the cheapest day for flights from phoenix to loreto mexico (use Tuseday) --next h2: How far are the flights from phoenix to loreto mexico ( Use 1,040.18) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from phoenix to loreto mexico
make a 4 paragraph blog about flights to loreto mexico from tijuana --first h2:How much are flights to loreto mexico from tijuana --next h2: How long are flights to loreto mexico from tijuana ( Use (2h44min)) next h2: What’s the cheapest day for flights to loreto mexico from tijuana (use Tuseday) --next h2: How far are the flights to loreto mexico from tijuana ( Use 1,182.86) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights to loreto mexico from tijuana
make a 4 paragraph blog about flights from san antonio to leon mexico --first h2:How much are flights from san antonio to leon mexico --next h2: How long are flights from san antonio to leon mexico ( Use (1h47min)) next h2: What’s the cheapest day for flights from san antonio to leon mexico (use Tuseday) --next h2: How far are the flights from san antonio to leon mexico ( Use 683.02) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from san antonio to leon mexico
make a 4 paragraph blog about flights from atlanta to leon mexico --first h2:How much are flights from atlanta to leon mexico --next h2: How long are flights from atlanta to leon mexico ( Use (3h17min)) next h2: What’s the cheapest day for flights from atlanta to leon mexico (use Tuseday) --next h2: How far are the flights from atlanta to leon mexico ( Use 1,474.71) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from atlanta to leon mexico
make a 4 paragraph blog about Flights from Chicago to Leon, Mexico --first h2:How much are Flights from Chicago to Leon, Mexico --next h2: How long are Flights from Chicago to Leon, Mexico ( Use (3h46min)) next h2: What’s the cheapest day for Flights from Chicago to Leon, Mexico (use Tuseday) --next h2: How far are the Flights from Chicago to Leon, Mexico ( Use 1,731.24) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Chicago to Leon, Mexico
make a 4 paragraph blog about Cheap flights to Leon, Guanajuato Mexico from LAX --first h2:How much are Cheap flights to Leon, Guanajuato Mexico from LAX --next h2: How long are Cheap flights to Leon, Guanajuato Mexico from LAX ( Use (2h58min)) next h2: What’s the cheapest day for Cheap flights to Leon, Guanajuato Mexico from LAX (use Tuseday) --next h2: How far are the Cheap flights to Leon, Guanajuato Mexico from LAX ( Use 1,307.40) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Cheap flights to Leon, Guanajuato Mexico from LAX
make a 4 paragraph blog about Cheap flights from Chicago to Leon Guanajuato Mexico --first h2:How much are Cheap flights from Chicago to Leon Guanajuato Mexico --next h2: How long are Cheap flights from Chicago to Leon Guanajuato Mexico ( Use (3h46min)) next h2: What’s the cheapest day for Cheap flights from Chicago to Leon Guanajuato Mexico (use Tuseday) --next h2: How far are the Cheap flights from Chicago to Leon Guanajuato Mexico ( Use 1,731.24) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Cheap flights from Chicago to Leon Guanajuato Mexico
make a 4 paragraph blog about dallas to leon mexico flights --first h2:How much are dallas to leon mexico flights --next h2: How long are dallas to leon mexico flights ( Use (2h16min)) next h2: What’s the cheapest day for dallas to leon mexico flights (use Tuseday) --next h2: How far are the dallas to leon mexico flights ( Use 936.75) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about dallas to leon mexico flights
make a 4 paragraph blog about phoenix to la paz mexico flights --first h2:How much are phoenix to la paz mexico flights --next h2: How long are phoenix to la paz mexico flights ( Use (1h52min)) next h2: What’s the cheapest day for phoenix to la paz mexico flights (use Tuseday) --next h2: How far are the phoenix to la paz mexico flights ( Use 723.35) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about phoenix to la paz mexico flights
make a 4 paragraph blog about Flights San Diego to La Paz, Mexico --first h2:How much are Flights San Diego to La Paz, Mexico --next h2: How long are Flights San Diego to La Paz, Mexico ( Use (2h0min)) next h2: What’s the cheapest day for Flights San Diego to La Paz, Mexico (use Tuseday) --next h2: How far are the Flights San Diego to La Paz, Mexico ( Use 799.72) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights San Diego to La Paz, Mexico
make a 4 paragraph blog about flights from lax to ixtapa mexico --first h2:How much are flights from lax to ixtapa mexico --next h2: How long are flights from lax to ixtapa mexico ( Use (2h48min)) next h2: What’s the cheapest day for flights from lax to ixtapa mexico (use Tuseday) --next h2: How far are the flights from lax to ixtapa mexico ( Use 1,217.66) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from lax to ixtapa mexico
make a 4 paragraph blog about Flights from Chicago to Ixtapa Mexico --first h2:How much are Flights from Chicago to Ixtapa Mexico --next h2: How long are Flights from Chicago to Ixtapa Mexico ( Use (3h52min)) next h2: What’s the cheapest day for Flights from Chicago to Ixtapa Mexico (use Tuseday) --next h2: How far are the Flights from Chicago to Ixtapa Mexico ( Use 1,784.42) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Chicago to Ixtapa Mexico
make a 4 paragraph blog about Flights from Dallas to Durango Mexico --first h2:How much are Flights from Dallas to Durango Mexico --next h2: How long are Flights from Dallas to Durango Mexico ( Use (2h21min)) next h2: What’s the cheapest day for Flights from Dallas to Durango Mexico (use Tuseday) --next h2: How far are the Flights from Dallas to Durango Mexico ( Use 984.76) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Dallas to Durango Mexico
make a 4 paragraph blog about flights from houston to durango mexico --first h2:How much are flights from houston to durango mexico --next h2: How long are flights from houston to durango mexico ( Use (2h9min)) next h2: What’s the cheapest day for flights from houston to durango mexico (use Tuseday) --next h2: How far are the flights from houston to durango mexico ( Use 879.17) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from houston to durango mexico
make a 4 paragraph blog about Los Angeles to Durango, Mexico flights --first h2:How much are Los Angeles to Durango, Mexico flights --next h2: How long are Los Angeles to Durango, Mexico flights ( Use (2h48min)) next h2: What’s the cheapest day for Los Angeles to Durango, Mexico flights (use Tuseday) --next h2: How far are the Los Angeles to Durango, Mexico flights ( Use 1,216.38) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Los Angeles to Durango, Mexico flights
make a 4 paragraph blog about Flights from Denver to Cozumel, Mexico --first h2:How much are Flights from Denver to Cozumel, Mexico --next h2: How long are Flights from Denver to Cozumel, Mexico ( Use (3h40min)) next h2: What’s the cheapest day for Flights from Denver to Cozumel, Mexico (use Tuseday) --next h2: How far are the Flights from Denver to Cozumel, Mexico ( Use 1,674.98) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Denver to Cozumel, Mexico
make a 4 paragraph blog about flights to cozumel mexico from houston --first h2:How much are flights to cozumel mexico from houston --next h2: How long are flights to cozumel mexico from houston ( Use (2h0min)) next h2: What’s the cheapest day for flights to cozumel mexico from houston (use Tuseday) --next h2: How far are the flights to cozumel mexico from houston ( Use 800.85) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights to cozumel mexico from houston
make a 4 paragraph blog about flights from houston to chihuahua mexico --first h2:How much are flights from houston to chihuahua mexico --next h2: How long are flights from houston to chihuahua mexico ( Use (2h17min)) next h2: What’s the cheapest day for flights from houston to chihuahua mexico (use Tuseday) --next h2: How far are the flights from houston to chihuahua mexico ( Use 946.08) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from houston to chihuahua mexico
make a 4 paragraph blog about Flights from LAX to Chihuahua, Mexico --first h2:How much are Flights from LAX to Chihuahua, Mexico --next h2: How long are Flights from LAX to Chihuahua, Mexico ( Use (1h32min)) next h2: What’s the cheapest day for Flights from LAX to Chihuahua, Mexico (use Tuseday) --next h2: How far are the Flights from LAX to Chihuahua, Mexico ( Use 547.68) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from LAX to Chihuahua, Mexico
make a 4 paragraph blog about Flights to Ciudad del Carmen, Mexico --first h2:How much are Flights to Ciudad del Carmen, Mexico --next h2: How long are Flights to Ciudad del Carmen, Mexico ( Use (16h27min)) next h2: What’s the cheapest day for Flights to Ciudad del Carmen, Mexico (use Tuseday) --next h2: How far are the Flights to Ciudad del Carmen, Mexico ( Use 8,426.23) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights to Ciudad del Carmen, Mexico
make a 4 paragraph blog about cheap flights from denver to cabo san lucas mexico --first h2:How much are cheap flights from denver to cabo san lucas mexico --next h2: How long are cheap flights from denver to cabo san lucas mexico ( Use (2h43min)) next h2: What’s the cheapest day for cheap flights from denver to cabo san lucas mexico (use Tuseday) --next h2: How far are the cheap flights from denver to cabo san lucas mexico ( Use 1,176.08) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about cheap flights from denver to cabo san lucas mexico
make a 4 paragraph blog about Flights from Seattle to Cabo San Lucas, Mexico --first h2:How much are Flights from Seattle to Cabo San Lucas, Mexico --next h2: How long are Flights from Seattle to Cabo San Lucas, Mexico ( Use (3h57min)) next h2: What’s the cheapest day for Flights from Seattle to Cabo San Lucas, Mexico (use Tuseday) --next h2: How far are the Flights from Seattle to Cabo San Lucas, Mexico ( Use 1,824.61) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Seattle to Cabo San Lucas, Mexico
make a 4 paragraph blog about Flights from Boston to Cabo San Lucas, Mexico --first h2:How much are Flights from Boston to Cabo San Lucas, Mexico --next h2: How long are Flights from Boston to Cabo San Lucas, Mexico ( Use (5h23min)) next h2: What’s the cheapest day for Flights from Boston to Cabo San Lucas, Mexico (use Tuseday) --next h2: How far are the Flights from Boston to Cabo San Lucas, Mexico ( Use 2,579.57) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Boston to Cabo San Lucas, Mexico
make a 4 paragraph blog about Flights from Orlando to Cabo San Lucas, Mexico --first h2:How much are Flights from Orlando to Cabo San Lucas, Mexico --next h2: How long are Flights from Orlando to Cabo San Lucas, Mexico ( Use (3h54min)) next h2: What’s the cheapest day for Flights from Orlando to Cabo San Lucas, Mexico (use Tuseday) --next h2: How far are the Flights from Orlando to Cabo San Lucas, Mexico ( Use 1,799.47) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Orlando to Cabo San Lucas, Mexico
make a 4 paragraph blog about flights from lax to aguascalientes mexico --first h2:How much are flights from lax to aguascalientes mexico --next h2: How long are flights from lax to aguascalientes mexico ( Use (2h58min)) next h2: What’s the cheapest day for flights from lax to aguascalientes mexico (use Tuseday) --next h2: How far are the flights from lax to aguascalientes mexico ( Use 1,307.40) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from lax to aguascalientes mexico
make a 4 paragraph blog about flights from chicago to aguascalientes mexico --first h2:How much are flights from chicago to aguascalientes mexico --next h2: How long are flights from chicago to aguascalientes mexico ( Use (3h46min)) next h2: What’s the cheapest day for flights from chicago to aguascalientes mexico (use Tuseday) --next h2: How far are the flights from chicago to aguascalientes mexico ( Use 1,731.24) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from chicago to aguascalientes mexico
make a 4 paragraph blog about Flights from Houston to Aguascalientes, Mexico --first h2:How much are Flights from Houston to Aguascalientes, Mexico --next h2: How long are Flights from Houston to Aguascalientes, Mexico ( Use (2h1min)) next h2: What’s the cheapest day for Flights from Houston to Aguascalientes, Mexico (use Tuseday) --next h2: How far are the Flights from Houston to Aguascalientes, Mexico ( Use 807.25) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about Flights from Houston to Aguascalientes, Mexico



"""
text = open("gpt3.txt", "w")
for x in string.rsplit("--"):
    print(x )
    text.writelines(x)
 
