import re
import openpyxl
import openai
import time
string = r"""make a 4 paragraph blog about flights from north carolina to australia --first h2:How much are flights from north carolina to australia --next h2: How long are flights from north carolina to australia ( Use (20h23min)) next h2: What’s the cheapest day for flights from north carolina to australia (use Tuseday) --next h2: How far are the flights from north carolina to australia ( Use 10,507.82) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from north carolina to australia
make a 4 paragraph blog about flgiths from st louis to australia --first h2:How much are flgiths from st louis to australia --next h2: How long are flgiths from st louis to australia ( Use (18h58min)) next h2: What’s the cheapest day for flgiths from st louis to australia (use Tuseday) --next h2: How far are the flgiths from st louis to australia ( Use 9,756.61) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flgiths from st louis to australia
make a 4 paragraph blog about flights from south africa to australia --first h2:How much are flights from south africa to australia --next h2: How long are flights from south africa to australia ( Use (12h42min)) next h2: What’s the cheapest day for flights from south africa to australia (use Tuseday) --next h2: How far are the flights from south africa to australia ( Use 6,446.56) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from south africa to australia
make a 4 paragraph blog about flights from seattle to australia --first h2:How much are flights from seattle to australia --next h2: How long are flights from seattle to australia ( Use (16h16min)) next h2: What’s the cheapest day for flights from seattle to australia (use Tuseday) --next h2: How far are the flights from seattle to australia ( Use 8,332.41) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from seattle to australia
make a 4 paragraph blog about flights from san francisco to australia --first h2:How much are flights from san francisco to australia --next h2: How long are flights from san francisco to australia ( Use (15h47min)) next h2: What’s the cheapest day for flights from san francisco to australia (use Tuseday) --next h2: How far are the flights from san francisco to australia ( Use 8,072.48) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from san francisco to australia
make a 4 paragraph blog about flights from seattle to australia --first h2:How much are flights from seattle to australia --next h2: How long are flights from seattle to australia ( Use (16h16min)) next h2: What’s the cheapest day for flights from seattle to australia (use Tuseday) --next h2: How far are the flights from seattle to australia ( Use 8,332.41) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from seattle to australia
make a 4 paragraph blog about flights from pakistan to australia --first h2:How much are flights from pakistan to australia --next h2: How long are flights from pakistan to australia ( Use (12h27min)) next h2: What’s the cheapest day for flights from pakistan to australia (use Tuseday) --next h2: How far are the flights from pakistan to australia ( Use 6313.66) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from pakistan to australia
make a 4 paragraph blog about flights from north carolina to australia --first h2:How much are flights from north carolina to australia --next h2: How long are flights from north carolina to australia ( Use (19h57min)) next h2: What’s the cheapest day for flights from north carolina to australia (use Tuseday) --next h2: How far are the flights from north carolina to australia ( Use 10239.06) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from north carolina to australia
make a 4 paragraph blog about flights from dallas to australia --first h2:How much are flights from dallas to australia --next h2: How long are flights from dallas to australia ( Use (18h6min)) next h2: What’s the cheapest day for flights from dallas to australia (use Tuseday) --next h2: How far are the flights from dallas to australia ( Use 9,301.64) miles --start every new paragraph with '*' --separate the questions on its own line --make an introduction about flights from dallas to australia



"""
text = open("gpt3.txt", "w")
for x in string.rsplit("--"):
    print(x )
    text.writelines(x)
 
